config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :products
  devise_for :users
  resources :searches
  resources :services
  resources :cars_todo_lists do 
    resources :service_todos do
      member do
          patch :completed
          patch :on_going
          patch :paid
      end
    end
  end
  
  resources :cars_todo_lists do 
    member do
      patch :ready_for_pickup
      patch :picked_up
    end
  end

  resources :cars_todo_lists do
    resources :comments
  end
  root "cars_todo_lists#index"

end

app/models/service.rb
class Service < ActiveRecord::Base
	


	validates :name ,					 presence: true
	validates :cost, 		 			presence: true, numericality: {greater_than_or_equal_to: 0}
end

app/controllers/services_controller.rb
class ServicesController < ApplicationController
  before_action :set_service, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!


  # GET /services
  # GET /services.json
  def index
    @services = Service.all
    @user = current_user
  end

 
  def show
    @user = current_user
  end

  # GET /services/new
  def new
    @service = Service.new
    @user = current_user
  end

  # GET /services/1/edit
  def edit
    @user = current_user
  end

  # POST /services
  # POST /services.json
  def create
    @user = current_user
    @service = Service.new(service_params)

    respond_to do |format|
      if @service.save
        format.html { redirect_to @service, notice: 'Service was successfully created.' }
        format.json { render :show, status: :created, location: @service }
      else
        format.html { render :new }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /services/1
  # PATCH/PUT /services/1.json
  def update
    respond_to do |format|
      if @service.update(service_params)
        format.html { redirect_to @service, notice: 'Service was successfully updated.' }
        format.json { render :show, status: :ok, location: @service }
      else
        format.html { render :edit }
        format.json { render json: @service.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /services/1
  # DELETE /services/1.json
  def destroy
    @service.destroy
    respond_to do |format|
      format.html { redirect_to services_url, notice: 'Service was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_service
      @service = Service.find(params[:id])
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def service_params
      params.require(:service).permit(:name, :cost)
    end
end

app/helpers/services_helper.rb
module ServicesHelper
end

app/views/services/_form.html.erb
<%= form_for(@service) do |f| %>
  <% if @service.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

      <ul>
      <% @service.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



<% if current_user.admin? %>
  <%= simple_form_for(@service) do |f| %>
         <% if @service.errors.any? %>
            <div id="error_explanation">
              <h2><%= pluralize(@service.errors.count, "error") %> prohibited this service from being saved:</h2>

              <ul>
              <% @service.errors.full_messages.each do |message| %>
                <li><%= message %></li>
              <% end %>
              </ul>
            </div>
          <% end %>

         <div class="form-group">
          <%= f.input :name, placeholder: "Name", required: true %>
          <%= f.input :cost, placeholder: "Price", required: true %>
          <%= f.button :submit, class: "btn btn-primary" %>
        </div>
        <%end%>
  <% end %>
<% end %>

app/views/services/edit.html.erb
<% if current_user.admin? %>
<h1>Editing Service</h1>

<%= render 'form' %>

<%= link_to 'Show', @service %> |
<%= link_to 'Back', services_path %>
<% end %>

app/views/services/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Services</h1>

<table class="table table-striped">
  
    <tr>
      <th>Name</th>
      <th>Cost</th>
      <% if current_user.admin?%>
      <th colspan="3"></th>
      <% end %>
    </tr>
  


    <% @services.each do |service| %>
      <tr>
        <td><%= link_to service.name, service%></td>
        <td><%= service.cost %></td>
   
        <% if current_user.admin?%>
        <td><%= link_to 'Edit', edit_service_path(service) %></td>
        <td><%= link_to 'Delete', service, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <%end %>
      </tr>
    <% end %>

</table>

<br>
<% if current_user.admin?%>
<%= link_to 'Add New Offered Service', new_service_path, class: "btn btn-default" %>
<%end %>

<%= link_to 'Back', :back , class: "btn btn-default" %>

app/views/services/new.html.erb
<% if current_user.admin? %>
<h1>New Service</h1>

<%= render 'form' %>

<%= link_to 'Back', services_path, class: "btn btn-default" %>
<%end %>

app/views/services/show.html.erb
<p id="notice"><%= notice %></p>


	  <h3><small>Service Name: <br></small><strong><%= @service.name %></strong></h3>
	  <hr>
	  <h3><small>Service Cost: <br></small><strong>PHP <%= @service.cost %>0</strong></h3>
	</p>
<hr>
<% if current_user.admin? %>
<%= link_to 'Edit', edit_service_path(@service), class: "btn btn-default" %> 

<% end %>
<%= link_to 'Back', services_path, class: "btn btn-default"  %>