config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :products
  devise_for :users
  resources :searches
  resources :services
  resources :cars_todo_lists do 
    resources :service_todos do
      member do
          patch :completed
          patch :on_going
          patch :paid
      end
    end
  end
  
  resources :cars_todo_lists do 
    member do
      patch :ready_for_pickup
      patch :picked_up
    end
  end

  resources :cars_todo_lists do
    resources :comments
  end
  root "cars_todo_lists#index"

end

app/models/cars_todo_list.rb
class CarsTodoList < ActiveRecord::Base
	has_many :service_todos
	belongs_to :user
	has_many :comments
	has_many :searches


#validations
	validates :image ,					 presence: true
	validates :car_plate_number, 		 presence: true, length: {maximum: 8, minimum: 1}
	validates :car_plate_number, format: { with: /[A-Z]{3}-[0-9]{3,4}/,
    message: "Follow (XXX-999/XXX-9999)" }

	validates :car_model, 		 	     presence: true
	validates :paid_amount,			 presence: true, numericality: {greater_than_or_equal_to: 0}

 	has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }
	

	validates_attachment_content_type :image, :content_type=> /\Aimage\/.*\Z/






	def ready_for_pickup?
  		!ready_for_pickup_at.blank? 
  	end

  	def pickedup?
  		 !pickedup_at.blank?
  	end

  	def has_image?
  		 !image.blank?
  	end
end

app/controllers/cars_todo_lists_controller.rb
class CarsTodoListsController < ApplicationController
  before_action :set_cars_todo_list, only: [:show, :edit, :update, :destroy, :ready_for_pickup, :picked_up]
  before_action :authenticate_user!
  # GET /cars_todo_lists
  # GET /cars_todo_lists.json

   respond_to :html, :json

  def index
    @cars_todo_lists = CarsTodoList.all
    @user = current_user
     respond_to :html, :json
    
  end

  # GET /cars_todo_lists/1
  # GET /cars_todo_lists/1.json
  def show
     @comments = Comment.where(cars_todo_list_id: @cars_todo_list)

  end

  # GET /cars_todo_lists/new
  def new
    if current_user.admin? || current_user.technician?
      @cars_todo_list = CarsTodoList.new
     
    else
      redirect_to cars_todo_lists_path
    end
  end

  # GET /cars_todo_lists/1/edit
  def edit
  end


  def ready_for_pickup
    CarsTodoMailer.ready_for_pickup(@cars_todo_list).deliver
    @cars_todo_list.update_attribute(:ready_for_pickup_at, Time.now)
    redirect_to @cars_todo_list, notice: "Car is Ready for Pickup."
  end   

  def picked_up
    CarsTodoMailer.picked_up(@cars_todo_list).deliver
    @cars_todo_list.update_attribute(:pickedup_at, Time.now)
    redirect_to @cars_todo_list, notice: "Car has been pickedup."
  end   



  # POST /cars_todo_lists
  # POST /cars_todo_lists.json
  def create
    @cars_todo_list = CarsTodoList.new(cars_todo_list_params)

    respond_to do |format|
      if @cars_todo_list.save
        CarsTodoMailer.new_cars_todo_list(@cars_todo_list).deliver
        format.html { redirect_to @cars_todo_list, notice: 'Cars todo list was successfully created.' }
        format.json { render :show, status: :created, location: @cars_todo_list }
      else
        format.html { render :new }
        format.json { render json: @cars_todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars_todo_lists/1
  # PATCH/PUT /cars_todo_lists/1.json
  def update
    respond_to do |format|
      if @cars_todo_list.update(cars_todo_list_params)
        format.html { redirect_to @cars_todo_list, notice: 'Cars todo list was successfully updated.' }
        format.json { render :show, status: :ok, location: @cars_todo_list }
      else
        format.html { render :edit }
        format.json { render json: @cars_todo_list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars_todo_lists/1
  # DELETE /cars_todo_lists/1.json
  def destroy
    @cars_todo_list.destroy
    respond_to do |format|
      format.html { redirect_to cars_todo_lists_url, notice: 'Cars todo list was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cars_todo_list
      @cars_todo_list = CarsTodoList.find(params[:id])
      @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cars_todo_list_params
      params.require(:cars_todo_list).permit(:car_plate_number, :car_model ,:image,:user_id, :paid_amount, :comments)
    end
end

app/helpers/cars_todo_lists_helper.rb
module CarsTodoListsHelper
end

app/views/cars_todo_lists/_form.html.erb
<div class="col-md-6">
<%= simple_form_for @cars_todo_list, html: { multipart: true} do |f| %>
  <% if @cars_todo_list.errors.any? %>
    <div id="error_explanation">
      <div class="alert alert-danger">
   <h2>Cars to Service <unsuccessful></unsuccessful>, 
     there is/are <%= pluralize(@cars_todo_list.errors.count, "error") %>.</h2>
     prevented this from saving

       <% @cars_todo_list.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
        <% end %>
    </div>
    </div>
<% end %> 

<div class="form-group">

<%= f.input :image, required: true %>
<%= f.input :car_plate_number, required: true %>
<%= f.input :car_model, required: true %>
<%= f.label :user, 'Select User Email:' %>
<%= f.collection_select :user_id, User.all, :id, :email  %><br><br>
<%= f.input :paid_amount,  required: true, label: 'Initial Paid Amount/Down Payment:' %>


<%= f.button :submit, class: 'btn btn-primary' %>

<%= link_to 'Back', cars_todo_lists_path, class: 'btn btn-default' %>
<% end %>
</div>
</div>

app/views/cars_todo_lists/_history.html.erb
<div class="well">

<% if current_user.admin? || current_user.technician? || current_user.cashier? %>
<h1 style="color: #888">Car Service History</h1>
<%= render 'tableheader' %>
  <%   @cars_todo_lists.order('created_at desc').each  do |cars_todo_list| %>
      <% if cars_todo_list.pickedup? %>
          <tr>
            <td> <%= link_to (image_tag cars_todo_list.image.url(:thumb)), cars_todo_list %> </td>
            <td> <%= link_to cars_todo_list.id, cars_todo_list %> </td>
            <td> <%= link_to cars_todo_list.car_plate_number, cars_todo_list %> </td>
            <td> <%= cars_todo_list.car_model %> </td>
          
            <td><font color="gray">Car has been Picked-up<span class="glyphicon glyphicon-ok-circle"> </span></font></td>
             <td><%= cars_todo_list.created_at.strftime("%I:%M %p %B-%d-%Y") %> </td>
     <% end %>
     
      </tr>
  <% end %>
  </div>
<% else %>
      <h1 style="color: #888">Car Service History</h1>
      <%= render 'tableheader' %>
        <%   @cars_todo_lists.order('created_at desc').each  do |cars_todo_list| %>
        <tr>
            <% if current_user.email == cars_todo_list.user.email %>
                  <% if cars_todo_list.pickedup? %>
                  <td> <%= link_to (image_tag cars_todo_list.image.url(:thumb)), cars_todo_list %> </td>
                  <td> <%= link_to cars_todo_list.id, cars_todo_list %> </td>
                  <td> <%= link_to cars_todo_list.car_plate_number, cars_todo_list %> </td>
                  <td> <%= cars_todo_list.car_model %> </td>
                  <td> <%= cars_todo_list.user.name %> </td>
                  <td><font color="gray">Car has been Picked-up<span class="glyphicon glyphicon-ok-circle"> </span></font></td>
                   <td><%= cars_todo_list.created_at.strftime("%I:%M %p %B-%d-%Y") %> </td>
                  <% end %>
          
          <% end %>
      </tr>
  <% end %>
<% end %>
  </div>
</table>
  

app/views/cars_todo_lists/_tableheader.html.erb
<table class="table table-striped">
<tr>
  <th>Car Image</th>
  <th>Service #</th>
  <th>Car Plate Number </th>
  <th>Car Model </th>
  <th>Car Owner </th>
  <th>Status </th>
  <th>Date Added </th>
</tr>

app/views/cars_todo_lists/edit.html.erb
<h1>Editing Cars Todo List</h1>

<%= render 'form' %>

<%= link_to 'Show', @cars_todo_list %> |
<%= link_to 'Back', cars_todo_lists_path %>

app/views/cars_todo_lists/index.html.erb
<div class="well">

<% if current_user.admin? || current_user.technician? || current_user.cashier? %>
<h1 style="color: #4D559A">Cars On Service </h1>
<%= render 'tableheader' %>
  <%  @cars_todo_lists.each do |cars_todo_list| %>
    <% if !cars_todo_list.pickedup?%>
      <tr>
        <td> <%= link_to (image_tag cars_todo_list.image.url(:thumb)), cars_todo_list %> </td>
        <td> <%= link_to cars_todo_list.id, cars_todo_list %> </td>
        <td> <%= link_to cars_todo_list.car_plate_number, cars_todo_list %> </td>
        <td> <%= cars_todo_list.car_model %> </td>
        <td> <%= cars_todo_list.user.email  %> </td>
          <% if cars_todo_list.ready_for_pickup? %>
              <td><font color="green">Car is Ready for Pick-up<span class="glyphicon glyphicon-ok-circle"> </span></font></td>
           <% else %>
               <td><font color="#337AB7">Car Service On-Going<span class="glyphicon glyphicon-ok-circle"> </span></font></td>
          <% end %>
        <td><%= cars_todo_list.created_at.strftime("%I:%M %p %B-%d-%Y") %> </td>
      </tr>
      <% end %>
     <% end %>
    </div>

<% else %>
<h1 style="color: #4D559A">Cars On Service </h1>
<%= render 'tableheader' %>
         <%  @cars_todo_lists.each do |cars_todo_list| %>
            <tr>
              <% if current_user.email == cars_todo_list.user.email%>
              <% if !cars_todo_list.pickedup?%>
              <td> <%= link_to (image_tag cars_todo_list.image.url(:thumb)), cars_todo_list %> </td>
              <td> <%= link_to cars_todo_list.id, cars_todo_list %> </td>
              <td> <%= link_to cars_todo_list.car_plate_number, cars_todo_list %> </td>
              <td> <%= cars_todo_list.car_model %> </td>
              <td> <%= cars_todo_list.user.name %> </td>
                <% if cars_todo_list.ready_for_pickup? %>
                   <td><font color="green">Car is Ready for Pickup<span class="glyphicon glyphicon-ok-circle"> </span></font></td>
                <% else %>
                     <td><font color="#337AB7">Car Service On-Going<span class="glyphicon glyphicon-ok-circle"> </span></font></td>
                <% end %>
               <td><%= cars_todo_list.created_at.strftime("%I:%M %p %B-%d-%Y") %> </td>
              <% end %>
              <% end %>
            </tr>
        <% end %>
<% end %>
</table>
</div>
<%= render 'history' %>

app/views/cars_todo_lists/new.html.erb
<% if current_user.admin? || current_user.technician? %>
	<h1>New Car To Service</h1>

	<%= render 'form' %>

	
	
<% end %>

app/views/cars_todo_lists/show.html.erb
<div class="well">
<p id="notice"><%= notice %></p>
<% if current_user.admin? || current_user.technician? %>

        <% if @cars_todo_list.ready_for_pickup? %>
            <%= link_to "Marked as Ready For Pickup", ready_for_pickup_cars_todo_list_path(@cars_todo_list.id), method: :patch, data: {confirm: "Are you Sure you want to mark car ready for pickup??"},class: "btn btn-primary disabled" %>
        <% else %>
            <%= link_to "Mark as Ready For Pickup", ready_for_pickup_cars_todo_list_path(@cars_todo_list.id), method: :patch, data: {confirm: "Are you Sure you want to mark car ready for pickup??"},class: "btn btn-primary" %>
        <%end %>
        <% if @cars_todo_list.pickedup? %>
           <%= link_to "Marked as Picked Up", picked_up_cars_todo_list_path(@cars_todo_list.id), method: :patch, data: {confirm: "Are you Sure you want to mark car ready for pickup??"},class: "btn btn-primary disabled" %>
        <% else %>
           <%= link_to "Mark as Picked Up", picked_up_cars_todo_list_path(@cars_todo_list.id), method: :patch, data: {confirm: "Are you Sure you want to mark car ready for pickup??"},class: "btn btn-primary" %>
        <% end %>
<% end %>
<% if current_user.email==@cars_todo_list.user.email || current_user.admin? || current_user.technician? || current_user.cashier? %>
<h2><strong>Plate Number:</strong>
  <%= @cars_todo_list.car_plate_number %>
</h2>
        <% if @cars_todo_list.has_image? %>
           <p><%= image_tag @cars_todo_list.image.url(:medium) %> </p>
        <% else %>
        No Car Image
        <% end %>


<p>
  <strong>Car model:</strong>
  <%= @cars_todo_list.car_model %>
</p>
<p>
<strong>Service ID:</strong>
  <%= @cars_todo_list.id %>
</p>
<p>
  <strong>Car Owner's Email:</strong>
  <%= @cars_todo_list.user.email %>
</p>
<p>
  <strong>Car Owner:</strong>
  <%= @cars_todo_list.user.name %>
</p>

<p>
  <strong>Contact_number:</strong>
  <%= @cars_todo_list.user.contact_number %>
</p>


<p>

  <strong>Total Bill:</strong> 
   <% total_bill = @cars_todo_list.service_todos.sum('price') %>
   <%= total_bill %>
</p>
<p>

<p>

  <strong>Total Paid Amount:</strong> 

   <% total = @cars_todo_list.service_todos.paid.sum('price') + @cars_todo_list.paid_amount %>
  <% if total > total_bill %>
    <%= total_bill %>
  <% else %>
    <%= total %>
  <%end %>
</p>

  <strong>Bill Balance:</strong> 
  <!-- computing the remaining balance)-->


  <% bill_balance = @cars_todo_list.service_todos.unpaid.sum('price') - @cars_todo_list.paid_amount %>
  <% if %>
  <% bill_balance < 0 %>
  0.00
  <%else %>
    <%= bill_balance %>
  <% end %>
</p>

<p>
<strong> Down Payment: </strong>
<%= @cars_todo_list.paid_amount %>


</p>

<p>
   <% if @cars_todo_list.pickedup? %>
              <td><em><font color="gray">Car has been Picked-up at <%= @cars_todo_list.pickedup_at.strftime("%I:%M %p %B-%d-%Y") %> </font></em></td>
         
  <% end %>
</p>
<div id="cars_todo_list_wrapper">
	<%= render @cars_todo_list.service_todos %>
	<div id="form">
		<%= render "service_todos/form" %>
	</div>
</div>
<p>

</p>
</div>
  <div class="well">
     <div id="comment">
        <strong><%= pluralize(@cars_todo_list.comments.count, "Comment") %>:</strong><hr>
        <% @comments.each do |comment| %>
          <div class="comment">
            <% if comment.user.admin? %>
                <p style="size:3px; color:#98173E"><strong>Admin</strong> commented:</p>
                <p style="size:3px; color:#98173E"><%= comment.content %>.<br> <font size="1"><em><%= time_ago_in_words(comment.created_at)%> ago</em></font> <br>  </p><hr>
           <% elsif comment.user.technician? %>
                <p style="size:3px; color:#248226"><strong>Technician</strong> commented:</p>
                <p style="size:3px; color:#248226"><%= comment.content %>.<br> <font size="1"><em><%= time_ago_in_words(comment.created_at)%> ago</em></font> <br>  </p><hr>
            <%else %>
              <p style="size:3px"><strong><%= comment.user.name %></strong> commented:</p>
              <p><%= comment.content %>.<br> <font size="1"><em><%= time_ago_in_words(comment.created_at)%> ago</em></font> <br>  </p><hr>
            <% end %>
        <%end %>
        <%= render 'comments/form' %>
     </div>
  </div>
<% if current_user.admin? || current_user.technician? %>
<%= link_to 'Edit', edit_cars_todo_list_path(@cars_todo_list), class: "btn btn-default" %> 
  <%= link_to "Delete", cars_todo_list_path, class: "btn btn-default", method: :delete, data: {confirm: "Are you sure?"} %>
<% end %>

<% end %>