config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :products
  devise_for :users
  resources :searches
  resources :services
  resources :cars_todo_lists do 
    resources :service_todos do
      member do
          patch :completed
          patch :on_going
          patch :paid
      end
    end
  end
  
  resources :cars_todo_lists do 
    member do
      patch :ready_for_pickup
      patch :picked_up
    end
  end

  resources :cars_todo_lists do
    resources :comments
  end
  root "cars_todo_lists#index"

end

app/models/service_todo.rb
class ServiceTodo < ActiveRecord::Base
  belongs_to :cars_todo_list

  validates :content, 				presence: true
  validates :price,           presence: true, numericality: {greater_than_or_equal_to: 0}

  scope :unpaid, -> {where(paid_at: nil)}
  scope :paid, -> {where.not(paid_at: nil)}
  
  def ongoing?
    !started_at.blank?
  end

  def completed?
  	!completed_at.blank? && !started_at.blank?
  end

  def paid?
  	!paid_at.blank?
  end

 

end

app/controllers/service_todos_controller.rb
class ServiceTodosController < ApplicationController
	before_action :set_cars_todo_list
	before_action :set_service_todo, except: [:create]
	

	def create
		@service_todo = @cars_todo_list.service_todos.create(service_todo_params)
		
		if @service_todo.save
			ServiceTodoMailer.new_service_todo(@service_todo).deliver
			redirect_to @cars_todo_list, notice: "Added Successfully, Please Update Bill Summary"
		else
			redirect_to @cars_todo_list, notice: "Input Error/ Price should be 0 or higher"
		end
	end

	def destroy
		if @service_todo.destroy
			flash[:success] = "Service Removed" 
		else
			flash[:error] = "Service Could not be removed"
		end
		redirect_to @cars_todo_list
	end

	def completed

		ServiceTodoMailer.completed(@service_todo).deliver
		@service_todo.update_attribute(:completed_at, Time.now)
		redirect_to @cars_todo_list, notice: "Service Completed"
	end 	

	def on_going
		ServiceTodoMailer.on_going(@service_todo).deliver
		@service_todo.update_attribute(:started_at, Time.now)
		redirect_to @cars_todo_list, notice: "Service On-going"
	end 	

	def paid
		ServiceTodoMailer.paid(@service_todo).deliver
		@service_todo.update_attribute(:paid_at, Time.now)
		redirect_to @cars_todo_list, notice: "Service Paid, Please Update the Bill Balance"
	end 	
	private

	def set_cars_todo_list
		@cars_todo_list = CarsTodoList.find(params[:cars_todo_list_id])
	end

	def service_todo_params
		params[:service_todo].permit(:content,:price)
	end
	def set_service_todo
		@service_todo = @cars_todo_list.service_todos.find(params[:id])
	end
end

app/helpers/service_todos_helper.rb
module ServiceTodosHelper
end

app/views/service_todos/_form.html.erb
<% if current_user.admin? || current_user.technician? || current_user.cashier? %>
	<%= form_for([@cars_todo_list, @cars_todo_list.service_todos.build]) do |f| %>
		<% if @cars_todo_list.ready_for_pickup? %>

		<% else %>
		<%= f.text_field :content, placeholder: "New Service" %>
		<%= f.text_field :price, placeholder: "Price" %>
		<%= f.submit %>
		<% end %>
	<% end %>
<% end %>




	

app/views/service_todos/_service_todo.html.erb
<div class="panel panel-default">
  <div class="panel-body">
    <b>Service:</b> <%= service_todo.content %><br>
    <b>Price:</b> <%= service_todo.price  %><br>
	<% if service_todo.completed? %>
		 <b>Status: </b><font color="green">ServiceCompleted<span class="glyphicon glyphicon-ok-circle"> </span></font>
	<% elsif service_todo.ongoing? %>
		 <b>Status: </b><font color="#337AB7">ServiceOnGoing<span class="glyphicon glyphicon-wrench"></span></font>
	<% else %>
		<b>Status: </b><span class="glyphicon glyphicon-asterisk"></span>n/a<span class="glyphicon glyphicon-asterisk"></span>
	<% end %>



	<% if service_todo.paid? %>
		<br><b>Paid: <font color="green"></b><span class="glyphicon glyphicon-ok-sign"></span></font>
	<% else %>
		<br><b>Paid: </b><span class="glyphicon glyphicon-remove-sign"></span>
	<% end %>
	

  </div>
  <div class="panel-footer">

<% if current_user.admin? || current_user.technician? %>
			<% if service_todo.ongoing? %>
				<%= link_to "Marked as On-Going", on_going_cars_todo_list_service_todo_path(@cars_todo_list, service_todo.id), method: :patch, data: {confirm: "Are you Sure you want to mark service as ON-GOING?"},class: "btn btn-primary disabled" %>
			<% else %>
				<%= link_to "Mark as On-Going", on_going_cars_todo_list_service_todo_path(@cars_todo_list, service_todo.id), method: :patch, data: {confirm: "Are you Sure you want to mark service as ON-GOING?"},class: "btn btn-primary" %>	
			<% end %>
		<% if service_todo.completed? %>
				<%= link_to "Marked as Complete", completed_cars_todo_list_service_todo_path(@cars_todo_list, service_todo.id), method: :patch, data: {confirm: "Are you sure you want to mark service as COMPLETED?"}, class: "btn btn-success disabled" %>
		<% else %>
			<%= link_to "Mark as Complete", completed_cars_todo_list_service_todo_path(@cars_todo_list, service_todo.id), method: :patch, data: {confirm: "Are you sure you want to mark service as COMPLETED?"}, class: "btn btn-success" %>
		<% end %>
<% end %>
	<% if current_user.cashier? || current_user.admin? %>
		<% if service_todo.paid? %>
				<%= link_to "Marked as Paid", paid_cars_todo_list_service_todo_path(@cars_todo_list, service_todo.id), method: :patch, data: {confirm: "Are you sure you want to mark service as COMPLETED?"}, class: "btn btn-info disabled" %>
		<% else %>
				<%= link_to "Mark as Paid", paid_cars_todo_list_service_todo_path(@cars_todo_list, service_todo.id), method: :patch,data: {confirm: "Are you sure you want to mark service as PAID?"},class: "btn btn-info" %>
		<% end %>
	<% end %>
	<% if @cars_todo_list.ready_for_pickup? %>

	<% else %>
		<% if current_user.admin? %>
			<%= link_to "Delete Service", cars_todo_list_service_todo_path(@cars_todo_list, service_todo.id), method: :delete, data: { confirm: "Are you sure yo want to DELETE service?"},class: "btn btn-danger" %>
		<% end %>
	<%end %>

  </div>
</div>