config/routes.rb
Rails.application.routes.draw do
  
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  resources :products
  devise_for :users
  resources :searches
  resources :services
  resources :cars_todo_lists do 
    resources :service_todos do
      member do
          patch :completed
          patch :on_going
          patch :paid
      end
    end
  end
  
  resources :cars_todo_lists do 
    member do
      patch :ready_for_pickup
      patch :picked_up
    end
  end

  resources :cars_todo_lists do
    resources :comments
  end
  root "cars_todo_lists#index"

end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-inverse">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
    
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to  "Intermobile", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
       <li><%= link_to "Home", root_path %>
       <% if user_signed_in? %>
       <li><%= link_to "Services" , services_path %></li>
       <li><%= link_to "Products" , products_path %></li>
         <% if current_user.admin? || current_user.technician? %>
             <li><%= link_to "New Car To Service" , new_cars_todo_list_path %></li>
            
             <li><%= link_to "Search" , new_search_path %></li>
        <% end %>
        <% end %>
      </ul>
   <!--   <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>-->
      <ul class="nav navbar-nav navbar-right">
    
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Account <span class="caret"></span></a>
    		   <ul class="dropdown-menu">
                      <% if user_signed_in? %>
                      
                      <li><%= link_to "Log out", destroy_user_session_path, method: "delete" %></li>
                      <li class="divider">
                      <li><center>Signed in as: 
                              <% if current_user.admin? %>
                                  <b style="color:#98173E">Admin</b></li>
                                  <% elsif current_user.technician? %>
                                  <b style="color:#1A711B"><%= current_user.email%></b></li>
                                  <% elsif current_user.cashier? %>
                                  <b style="color:#1A711B"><%= current_user.email%></b></li>
                              <%else %>
                                <%= current_user.email %></li>
                              <% end %>
                      <% else %>
                       <li><%= link_to "Log In",  new_user_session_path %></li>
                      </li>
                      <% end %>
                </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/_sidebar.html.erb
<!--  <% if user_signed_in? %>
<div class="container">
  <div class="transitions-enabled" id="sidepanel">
     <div class="box panel panel-default">
     	
          <div class="panel-body">
            <li><strong>Welcome!</strong></li>
      <% if current_user.admin? %>
		   <li style="color:#98173E"> Admin </li>
       <% elsif current_user.technician? %>
       <li style="color:#1A711B"> Technician </li>
      <% elsif current_user.cashier? %>
       <li style="color:#1A711B"> Cashier </li>
      <% else %>
      <li><%= current_user.name %></li>
      <% end %>
  <%= image_tag current_user.avatar %>
			<hr>
			<li><%= link_to "Change Account Details", edit_user_registration_path %></li>
			
          </div>
      </div>
  </div>
</div>
<% else %>
<%end %> -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Intermobile</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  
  <%= csrf_meta_tags %>

</head>
<body>
<% if user_signed_in? %>
	  <%= render 'layouts/header' %>

	  
		
	       <div class="container">
	       <div class="row">
		      \
		     	<div class="col-xs-8 col-sm-9 col-md-9">
	     		  
						<%= yield %>
				  
			    </div>
			</div>
			
			</div>
	
	<% else %>
	  <%= render 'layouts/header' %>

	  </div><div class="container">
		<p class="notice"><%= notice %></p>
	       <p class="alert"><%= alert %></p>
	       
	    
		   
				<%= yield %>
				</div>
			
	<% end %>
</body>
</html>